title: Mohanbabu - Senior DevOps Professional
description: Mohanbabu is a highly skilled Human Senior DevOps professional with a passion for contributing to Healthcare and Non-profit organizations. Explore his expertise and commitment to excellence.
show_downloads: true
google_analytics: UA-XXXXXXXXX-1  # Replace with your Google Analytics tracking code
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme 
